version: "3.9"

services:
  postgres_db:
    image: "postgres:14"
    container_name: zoo_database
    environment:
      POSTGRES_DB: zoo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
#      - .:/docker-entrypoint-initdb.d
      - zoo_db-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    expose:
      - "5431"
    networks:
      - server_net
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 3

  zoopunk_server:
    container_name: zoopunk_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "33333:8080"
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - server_net

networks:
  server_net:
    name: server_net

volumes:
  zoo_db-data: